CronosTourism/src/main/java/br/puc/pss/controller/LoginController.java
package br.puc.pss.controller;

import br.puc.pss.DAO.AlertaDAO;
import br.puc.pss.DAO.AlertaDAOImpl;
import br.puc.pss.DAO.UsuarioDAO;
import br.puc.pss.DAO.UsuarioDAOImpl;
import br.puc.pss.common.SistemaCommon;
import br.puc.pss.common.Util;
import br.puc.pss.obj.Alerta;
import br.puc.pss.obj.Usuario;
import org.apache.log4j.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 * Created with IntelliJ IDEA.
 * Pontifícia Universidade Católica do Rio de Janeiro - PUC-Rio
 * User: Ariel Escobar
 * Date: 11/15/13
 * Time: 3:18 PM
 */
@ManagedBean(name = "LoginController")
@ViewScoped
public class LoginController {
    private UsuarioDAO usuarioDB = new UsuarioDAOImpl();
    private AlertaDAO alertaDAO = new AlertaDAOImpl();

    static final Logger LOGGER = Logger.getLogger(LoginController.class);

    private Usuario objUsuario;
    private String nick;
    private String password;

    public LoginController() {
        this.objUsuario = new Usuario();
    }

    public Usuario getObjUsuario() {
        return objUsuario;
    }

    public void setObjUsuario(Usuario objUsuario) {
        this.objUsuario = objUsuario;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void ingresar() {
        try {

            Usuario usuarioIngreso = usuarioDB.autenticarUsuario(nick, password);
            if (usuarioIngreso != null) {
                LOGGER.info(usuarioIngreso.getNomeusuario());
                objUsuario = usuarioIngreso;
                HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
                session.setAttribute(SistemaCommon.S_USUARIO, usuarioIngreso);
                Util.redirecionar("/adm/usuario.jsf");
            } else
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
                        "Los datos son incorrectos", "Los datos son incorrectos"));
        } catch (SQLException e) {
            LOGGER.fatal("Error al consultar la BD ", e);
        }
    }

    public void salir() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
        session.invalidate();
        Util.redirecionar("/login.jsf");
    }

    public Usuario getUsuarioActual() {
        return SistemaCommon.getUsuarioActual();
    }

    private String alertaTit;
    private String style;

    public String getAlertaTit() {

        return alertaTit;
    }

    public void setAlertaTit(String alertaTit) {
        this.alertaTit = alertaTit;
    }

    public String getStyle() {

        return style;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public void getAlertas() {
        ArrayList<Alerta> lstAlertas = new ArrayList<Alerta>();
        try {
            lstAlertas = alertaDAO.getByEstado("AC");
            if (lstAlertas.size() > 0) {
                style = "color: red; font-weight:bold;";
                alertaTit = lstAlertas.size() + " Alertas";
            } else {
                style = "color: black;";
                alertaTit = "0 Alertas";
            }
        } catch (SQLException e) {
            LOGGER.error("Erro lir dados alertas", e);
        }

    }
}

CronosTourism/src/main/webapp/WEB-INF/facelets/templates/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<ui:composition>

    <h:form id="formPrincipal">
        <p:poll interval="3"
                listener="#{LoginController.getAlertas}" update=":formPrincipal:menu" />
        <p:menubar id="menu">
            <p:menuitem value="Usuarios" url="/adm/usuario.jsf" icon="ui-icon-wrench" />
            <p:menuitem value="Empregados" url="/adm/empregado.jsf" icon="ui-icon-person" />
            <p:menuitem value="Pacotes" url="/adm/pacote.jsf" icon="ui-icon-suitcase" />
            <p:menuitem value="Eventos" url="/adm/evento.jsf" icon="ui-icon-clock" />
            <p:menuitem value="#{LoginController.alertaTit}" style="#{LoginController.style}" url="/adm/alerta.jsf" icon="ui-icon-mail-closed" ></p:menuitem>


            <f:facet name="options">
                <b><p:outputLabel style="margin-right:10px; margin-top: 20px; " value="Usuario: "/></b>

                <p:commandLink style="margin-right:10px" value="#{LoginController.usuarioActual.nome} #{LoginController.usuarioActual.sobrenome}"/>
            </f:facet>

            <p:menuitem value="Salir" icon="ui-icon-close" actionListener="#{LoginController.salir}"/>
        </p:menubar>
    </h:form>
</ui:composition>
</html>

CronosTourism/src/main/webapp/WEB-INF/facelets/templates/principal.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html">

<h:head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title><ui:insert name="PUC RIO - PSS"/></title>
    <link rel="stylesheet" href="../css/style.css" type="text/css"/>
    <link rel="shortcut icon" type="image/x-icon" href="../images/CronosLoso.png"/>

</h:head>
<h:body>

    <div id="layout" style="width: auto; margin: auto; padding: 10px;">
        <div id="header" style="width: auto;">
            <div id="cabezera">
                <div id="logo">
                    <img src="../images/CronosLoso.png" alt="#" height="70" width="100"/>
                </div>
                <div id="empresa">
                    <div id="tituloSistema">
                        TRABALHO FINAL
                    </div>
                    <p style="text-align: center;">PUC-RIO PSS</p>

                </div>
            </div>
            <ui:include src="menu.xhtml"/>
        </div>

        <div id="content" style="width: auto; margin: auto;">
            <ui:insert name="content">
                <span>SISTEMA HOTEL PSS</span>
            </ui:insert>
        </div>

        <div id="footer" style="width: auto; text-align: center;">
            <p:separator id="separator"/>
            <p>Ariel Escobar Endara <a href="aendara@inf.puc-rio.br"> aendara@inf.puc-rio.br</a> Trabalho Final PSS - PUC-RIO - 2013
            </p>
        </div>
    </div>

</h:body>
</html>